Aduell
duellal/web-module-project-class-components pull request #1
Opened 2022-08-22 22:20 UTC by duellal

2022-08-23 14:42 UTC, jduell12 requested changes
Overall really good! Some comments for streamlining. The only change I need you to change is the id that you're creating for the todo. The length of the array could have the same length at some point whereas if you set the id as the current Date then it won't ever be the same since time goes forward and doesn't repeat.

2022-08-23 14:42 UTC, jduell12 commented on frontend/components/App.js
> +   })
This works well but you could streamline it even more by: 
`this.setState({
        todos: this.state.todo.map(item => {...})
    })`

2022-08-23 14:42 UTC, jduell12 commented on frontend/components/App.js
> +      return(item)
You don't need the parentheses here

2022-08-23 14:42 UTC, jduell12 commented on frontend/components/App.js
> +      id: this.state.todos.length,
You want this id to be unique so a better option might be a timestamp here since the time won't be the same but the length could repeat itself

2022-08-23 14:42 UTC, jduell12 commented on frontend/components/App.js
> +      todos: newTodos
Since the variable newTodos isn't getting changed you can use
`this.setState({
    todos: [...this.state.todos, newTodo]
})`
instead

2022-08-23 14:42 UTC, jduell12 commented on frontend/components/Form.js
> +        placeholder='Todo'/>
Did you need a value here for the form? Where it's related to the props.input value in state

2022-08-23 14:42 UTC, jduell12 commented on frontend/components/Todo.js
> +      onClick={this.handleClick}>
You can streamline this by:
`onClick={()=> {this.props.toggleTodo(this.props.todo.id)}}`
then you wouldn't need the handleClick function

2022-08-24 21:57 UTC, duellal commented
Added the form value. I left everything else the same. Even though it probably is more streamlined to put some of the things inside of the functions, for me, it's more readable the way I have it.

2022-08-25 13:41 UTC, jduell12 approved these changes

2022-08-26 15:24 UTC, merged